### PR TITLE
update shebang

### PR DESCRIPTION
**Pull request by jeongseup**
for working, need to update `#!/bin/bash` in startup.sh

### CODE REVIEW

**Review by MicahZoltu — APPROVED** [review]

**Comment by MicahZoltu** [comment]
Nothing in the script is `bash` specific?  All of it works in `sh`?

**Comment by MicahZoltu** [comment]
Going to opportunistically merge this since it seems quite reasonable and I welcome someone trying to fix the script!

**Comment by jeongseup** [comment]
Thank you for merging my PR. We have to comply with the format rules 😄 

```
Nothing in the script is bash specific? All of it works in sh?
```
=> Yes !! The problem is just caused by missing out "!"

**Comment by Jeongseup** [comment]
> 

Yes !! The problem is just caused by missing out "!"

**Pull request merged**
